/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testemptyproject.app;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

@DisplayName("MessageUtils Test")
class MessageUtilsTest {
    @DisplayName("Test getMessage()")
    @Test void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
