name: Run Tests

on:
  push:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 19

      - name: Build and test
        run: |
          gradle test --distribution=plain
